# 1. Why Numpy?
Because they reveal these 5 important core purposes:
1. Speed
2. Structure
3. Vectorization
4. Math
5. AI Foundation

### ==============================================================

# 0. How to Create Numpy Arrays?

In [113]:
a = [1,2,3,4,5.55]
type(a)

list

In [18]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


### ==============================================================

## 1. Efficient Numerical Computation (Speed Engine)

In [20]:
%%time
b = a+a*4
b

CPU times: total: 0 ns
Wall time: 0 ns


array([ 5, 10, 15])

In [22]:
import numpy as np
import time

size = 10000000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# List timing
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
#print(result_list)
list_time = time.time() - start

# NumPy timing
start = time.time()
result_array = arr1 + arr2
#print("***************")
#print(result_array)
numpy_time = time.time() - start

print(f"List Time: {list_time:.5f} seconds")
print(f"NumPy Time: {numpy_time:.5f} seconds")
print(f"Speed Difference: {list_time / numpy_time:.2f}x faster")

List Time: 1.41348 seconds
NumPy Time: 0.05523 seconds
Speed Difference: 25.59x faster


### Purpose:
1. Handle large-scale calculations fast

### Why Not do the with same operations with other Data Structures like List?
1. Python lists → slow (loop-based)
2. NumPy → optimized (C-level execution)

### ==============================================================

## 2. Multi-Dimensional Data Handling (Data Structure)

In [27]:
arr_demo = np.array([[[1,2,3,4]]])
arr_demo.ndim

3

In [34]:
arr_demo = np.array([[1,2],[3,4],[5,6]])
arr_demo.ndim

2

In [42]:
arr = np.array([[[1,2],[3,4],[5,6]]])
print(arr.shape)

(1, 3, 2)


#### Why it matters:
To handle...
* 2D → matrix(black & white images)
* 3D+ → tensors (colored images)

### ==============================================================

## 3.Vectorized Operations

##### Without Numpy Array

In [43]:
arr = np.array([1, 2, 3])
result = []
for i in range(len(arr)):
    result.append(arr[i] * 2)
print(result)

[np.int64(2), np.int64(4), np.int64(6)]


##### With Numpy Arrays

In [44]:
result = arr * 2
result

array([2, 4, 6])

## Same work… but NumPy removes the repetition.

### Real-Life Vectorization Examples:
1. ATM Queue vs Online Transfer - 
"One person uses ATM at a time Vs Everyone sends money instantly using UPI.”

##### Takeaway:
* Loop → sequential
* Vectorization → parallel

2. Washing Clothes One-by-One vs Washing Machine

In [ ]:
arr = np.array([1, 2, 3, 4])
arr + 10

## Vectorization means -> Same work… but NumPy...
### Removes the repetition and choose to go with parallel execution.

### ==============================================================

## 4. Mathematical & Statistical Operations

In [29]:
arr = np.array([1, 2, 3, 4])

print(np.mean(arr))
print(np.std(arr))

2.5
1.118033988749895


#### Purpose:
* Mean, variance, std → ML basics
* Linear algebra → Deep Learning core

#### Note:
“All intelligence in AI comes from math - NumPy executes it.”

### ==============================================================

## 5. Foundation for Machine Learning & Deep Learning

In [30]:
np.dot(X, W)

NameError: name 'X' is not defined

### Purpose:
* Act as the base layer for all AI libraries

### Why it matters:
* TensorFlow
* PyTorch

### ==============================================================

### ==============================================================

### Problem Statement: We are going to build a simple brain… using only NumPy

### Problem:
Predict output using:

In [ ]:
y = 2x + 3

### Step 1: Import Necessary Libraries

In [40]:
import numpy as np

### Step 2: Data Collection

In [51]:
X = np.array([[1], [2], [3], [4]])  #X = Inputs
y = np.array([[5], [7], [9], [11]]) #y = actual outputs

### Step 3: Data Understanding

In [76]:
X,y

(array([[1],
        [2],
        [3],
        [4]]),
 array([[ 5],
        [ 7],
        [ 9],
        [11]]))

In [46]:
X.shape,y.shape

((4, 1), (4, 1))

In [48]:
X.ndim,y.ndim

(2, 2)

### Step 4: Data Preparation, Model Building, Model Training

### Phase 1: The Core 4-Step SETUP STAGE

##### 4.1 Initialize weights randomly

In [ ]:
np.random.randn()

In [71]:
w = np.random.randn(1,)
b = np.random.randn(1)

print("Initial w:", w)
print("Initial b:", b)

Initial w: [-0.97715708]
Initial b: [0.28409326]


##### 4.2 Forward Pass (Prediction)

In [63]:
def forward(X, w, b):
    return np.dot(X, w) + b

y_pred = forward(X, w, b)
print("Predictions:\n", y_pred)

Predictions:
 [[-1.54825327]
 [-1.49998968]
 [-1.45172609]
 [-1.40346249]]


##### 4.3 Loss Function (Error)

In [64]:
def loss(y, y_pred):
    return np.mean((y - y_pred) ** 2)

print("Loss:", loss(y, y_pred))

Loss: 94.55347633733007


##### 4.4 Backpropagation (Manual Gradient)

In [65]:
def gradients(X, y, y_pred):
    n = len(X)
    
    dw = (-2/n) * np.dot(X.T, (y - y_pred))
    db = (-2/n) * np.sum(y - y_pred)
    
    return dw, db

### Phase 2: The Actual Training Phase

In [66]:
print("Before Training:", forward(np.array([[5]]), w, b))

Before Training: [[-1.3551989]]


In [67]:
learning_rate = 0.01

for i in range(1000):
    y_pred = forward(X, w, b)
    
    dw, db = gradients(X, y, y_pred)
    
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss(y, y_pred)}")

Epoch 0, Loss: 94.55347633733007
Epoch 100, Loss: 1.1392232555734338
Epoch 200, Loss: 0.6254199117037537
Epoch 300, Loss: 0.3433480347613236
Epoch 400, Loss: 0.18849395545037267
Epoch 500, Loss: 0.10348092210874424
Epoch 600, Loss: 0.05680978583578704
Epoch 700, Loss: 0.031187891458064873
Epoch 800, Loss: 0.01712177856842562
Epoch 900, Loss: 0.00939965119926037


In [68]:
print("After Training:", forward(np.array([[5]]), w, b))

After Training: [[13.12315137]]


### So... Learning = Updating weights and bias to reduce error.

### ==============================================================

## Step 5: Result

In [69]:
print("Final w:", w)
print("Final b:", b)

Final w: [[2.05978576]]
Final b: [[2.82422259]]


##### Expected Result:
* w ≈ 2
* b ≈ 3

# We just built a Neural Network… without TensorFlow or PyTorch.

### ==============================================================

### Anyway, the Final Verdict

##### Why Numpy?
Because they reveal these 5 important core purposes:
1. Speed - "100 Workers vs 1 Worker”
2. Structure - Machines don’t see tables… they see grids
3. Vectorization - Teaching Entire Class at Once
4. Math - "Calculator for Scientists"
5. AI Foundation

#### Memory hook - mnemonic-style
* SSVMA - SSV Martial Arts

# The END!!